schema: moderne-api-schema.graphql
extensions:
  endpoints:
    Remote Moderne GraphQL Endpoint:
      url: https://api.app.moderne.io/
      headers:
        Authorization: Bearer ${MODERNE_API_TOKEN}
      introspect: true
