name: CI
on:
  push:
    branches: main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: test (Python ${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tests
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
