name: moderne-schema-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6AM UTC (1AM EST)

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Update `moderne-api-schema.graphql`
      run: node moderne-api-schema-sync.js
      env:
        MODERNE_API_TOKEN: ${{ secrets.MODERNE_TOKEN }}
    - name: Commit change to `moderne-api-schema.graphql`
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update `moderne-schema.graphql`
