name: weekday-campaign

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 1,3,4,5 # 11pm UTC (6PM EST) on Monday, Wednesday, Thursday, Friday

jobs:
  pick-campaign:
    depends-on: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install `omega-moderne-client`
        run: |
          python -m pip install --upgrade pip
          pip install .[cli]
          pip install .[github-scripts]
      - name: Pick campaign to execute
        run: |
          CAMPAIGN_NAME = $(/.github/scripts/pick-campaign-to-run.py)
          if [ $? -ne 0 ]; then
            echo "No campaign to run"
            exit 0
          fi
          echo "CAMPAIGN_NAME=$CAMPAIGN_NAME"
          echo "CAMPAIGN_NAME=$CAMPAIGN_NAME" >> $GITHUB_ENV
    outputs:
      campaign-name: ${{ env.CAMPAIGN_NAME }}

  run-campaign-scheduled:
    needs: [pick-campaign]
    runs-on: ubuntu-latest
    uses: ./.github/workflows/recurring-campaign-base.yml
    with:
      campaign_identifier: ${{ needs.pick-campaign.outputs.campaign-name }}
